'''La idea es de usar este documento para hacer el mapa
a partir de ruido perlin generado con el archivo noiseGenerator.py'''

from noiseGenerator import *

noise = OpenSimplexNoise("noiseTest", 100, 100, 3, 5)
noise.generateNoiseArray()
noise.mapArbValueToColorValue()

#Pegué esta function pero hay que cambiarle casi todo. El nombre, la descripción, el contenido etc.
#Lo importante de lo que pegué son los "for j in ..."

def mapArbValueToColorValue(self):
    '''The values generated by generateNoiseArray are values from -1.50 to 1.50 aprox
    We need the to go from 0 to 255 to use the, as colors
    This method does that
    We may try to use the map function instead later
    '''
    for j in range(len(self.noiseArray)):
        for i in range(len(self.noiseArray[j])):
            num = round(255 / 2 * self.noiseArray[j][i] + 255 / 2)
            if num > 255:
                num = 255
            if num < 0:
                num = 0
            self.noiseArray[j][i] = num
            
            
            
            
            
noise.saveAsPNG()
noise.saveSeedAsTxtFile()
